config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root "static#home"

  get '/proposez_votre_luli', to: 'static#association_invite'

  get '/presentation', to:'static#presentation'


  resources :static, only: [:home]
  resources :users, except: [:index, :new, :create]
  resources :contacts, only: [:new, :create], path: 'contact'
  resources :lulis do
    resources :bids,except: [:index, :edit, :destroy]
  end

end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :bidder, foreign_key:"bidder_id", class_name: "User"
  belongs_to :luli

  validates :contact_name, FIELD_VALIDATIONS
  validates :contact_role, FIELD_VALIDATIONS
  validates :contact_email, presence: true, format: { with: EMAIL_REGEX}
  validates :contact_number, phone: true
  validates :motivation, TEXT_VALIDATIONS
  validates :argument, TEXT_VALIDATIONS
  validates :comment, length: 1..5000
  validates :luli_id, uniqueness: { scope: :bidder_id,
      message: "Vous avez une demande en cours pour ce Luli. Veuillez attendre le retour de l'association." }


  validates :status, inclusion: { in: %w(pending accepted refused),
    message: "Veuillez choisir parmi 'pending', 'accepted', 'refused'." }

  after_create :new_bid
  #########instance methods here##############
  def pending
    status == 'pending'
  end

  def accepted
    status == 'accepted'
  end

  def refused
    status == 'refused'
  end
  #########mailing methods here###############
  def new_bid
    BidMailer.new_bid_notification(self).deliver_now
    BidMailer.new_bid_confirmation(self).deliver_now
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :get_current_user
  before_action :get_current_luli
  before_action :get_current_bid, only: [:show, :update]
  before_action :can_offer_bid, only: [:new, :create]
  before_action :can_read_bid, only:[:show]


  def show
  end

  def new
    @bid = Bid.new(bidder: @user, luli: @luli)
  end

  def create
    @bid = Bid.new(bid_attributes.merge(bidder: @user, luli: @luli,status: "pending"))
    if @bid.save
      flash[:success] = "La demande de mise en relation a bien été prise en compte."
      redirect_to luli_bid_path(@luli.id, @bid.id)
    else
      flash[:notice] = "Demande non enregistrée. Auriez-vous rempli tous les champs ?"
      render 'new'
    end
  end

  def update
    @bid.update(status_param)
    flash.now[:success]="La modification a bien été prise en compte"

    if @bid.status == "accepted"
      @luli.update(active: false)
      flash[:success] = "Félicitations ! Votre luli a abouti à un partenariat ! Celui-ci sera désormais visible dans la liste des lulis archivés."
      redirect_to luli_path(@luli)
    end
  end

  private

  def can_read_bid
    unless (@user == @bid.bidder)||(@user == @luli.broker)||(@user.admin)
      flash[:notice] = "Vous n'avez pas accès à cette information."
      redirect_to luli_path(@bid.luli)
    end
  end

  def can_offer_bid
    unless current_user.org_type == "entreprise"
      flash[:success] = "Vous pouvez contacter l'association directement."
      redirect_to root_path
    end
  end

  def get_current_bid
    @bid = Bid.find(params[:id])
  end

  def get_current_luli
    @luli = Luli.find(params[:luli_id])
  end

  def status_param
    params.permit(:status)
  end

  def bid_attributes
    params.permit(:contact_name, :contact_role, :contact_email, :contact_number, :motivation, :argument, :comment, :request, :comment, :contact_name, :contact_number, :contact_email)
  end


end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/bids/_bid_form.html.erb
  <%= form_tag url_for(action: 'create'), method: 'POST', class:"form-container" do %>
<div class="row no-gutters">
  <div class="form-col">
    <div class="row no-gutters">
    <h2 class="new-luli-title mb-4">Votre demande</h2>
    <div class="form-group col-md-10">
        <%= label_tag 'name', 'Nom du luli pour lequel vous demandez une mise en relation :'%>
        <%= text_field_tag 'name', @luli.name, readonly: true, class: "form-control" %>
    </div>
    <div class="form-group col-md-10">
        <%= label_tag 'luli_association_name', "Proposé par l'association :"%>
        <%= text_field_tag 'luli_association_name', @luli.broker.org_name, readonly: true, class: "form-control" %>
    </div>
    <div class="form-group col-md-12">
      <%= label_tag 'motivation', 'En quoi ce Luli vous intéresse-t-il ?*'%>
      <%= text_area_tag 'motivation', "Entre 5 et 5000 caractères", class: "form-control" %>
    </div>
    <div class="form-group col-md-12">
      <%= label_tag 'argument', 'Que pouvez-vous apporter à ce projet ?*'%>
      <%= text_area_tag 'argument', "Entre 5 et 5000 caractères", class: "form-control"%>
    </div>
    <div class="form-group col-md-12">
      <%= label_tag 'comment', 'Vos remarques'%>
      <%= text_area_tag 'comment', "Entre 1 et 5000 caractères", class: "form-control"%>
    </div>
  </div>
</div>

  <div class="form-row">
      <h2 class="mb-4">Contact</h2>
      <div class="fields-contact form-group col-md-10">
        <%= label_tag 'org_name', 'Nom de votre entreprise*'%>
        <%= text_field_tag 'org_name', @bid.bidder.org_name, readonly: true, class: "form-control" %>
      </div>
      <div class="form-group col-md-6">
        <%= label_tag 'contact_name', 'Personne à contacter*'%>
        <%= text_field_tag 'contact_name', @bid.bidder.name, class: "form-control", placeholder: 'Entre 1 et 100 caractères' %>
      </div>
      <div class="form-group col-md-6">
        <%= label_tag 'contact_role', 'Rôle*'%>
        <%= text_field_tag 'contact_role', @bid.bidder.role, class: "form-control", placeholder: 'Entre 1 et 100 caractères' %>
      </div>
      <div class="form-group col-md-6">
        <%= label_tag 'contact_number', 'Uniquement les chiffres sans indicadif ni séparateur. Ex: 0607070750'%>
        <%= text_field_tag 'contact_number', @bid.contact_number, class: "form-control", placeholder: '10 chiffres' %>
      </div>
      <div class="form-group col-md-6">
        <%= label_tag 'contact_email', 'Email*'%>
        <%= text_field_tag 'contact_email', @bid.bidder.email, class: "form-control", placeholder: 'exemple@email.com' %>
      </div>
      <p class="font-italic mt-5 ml-3">(*)Champs obligatoires.</p>
  </div>


  <div class="luli-btn">
    <%= button_to "Envoyer", luli_bids_path(@luli.id, @bid.id), method: :post, class: "btn btn-primary" %>
  </div>

<% end %>
</div>

app/views/bids/_list.html.erb
<% bid_list.each do |bid| %>
<div class="container mb-5 mt-5">
<div class=" row mb-2 no-gutters">
    <div class="col-md-12">
      <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative bg-white">
        <div class="col p-4 d-flex flex-column position-static border-right border-info ml-3">
          <h3 class="mb-0 resizing-title"><%=bid.luli.name%></h3><br>
          <div class="mb-1 text-muted">
            <p>Emise par <%= bid.bidder.first_name%> de l'entreprise <%= bid.bidder.org_name%></strong></p>
            <p>Publié le: <%= bid.created_at.to_date%></p>
           
          </div>
          <%= link_to "Voir la demande", luli_bid_path(bid.luli, bid), class:"mr-2"%>
        </div>
        <div class="col-md-6 d-none d-lg-block">
            <% if bid.luli.cover_photo.attached?%> <%= image_tag bid.luli.cover_photo, style:'object-fit: cover; height: 280px; width: 100%; display: block;' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/bids/create.html.erb
<h1>Bids#create</h1>
<p>Find me in app/views/bids/create.html.erb</p>

app/views/bids/new.html.erb
<h1 class="text-center mt-5 mb-5">Demande de mise en relation</h1>

<%= render "bid_form" %>

app/views/bids/show.html.erb
<div class="container text-secondary">
  <h2 class="mt-5">Demande de mise en relation pour le luli <br>"<%= link_to @luli.name, luli_path(@luli)%>"</h2>
  <div class="bid-show">
    <% if @bid.status == "pending"%>
<p><u>Statut de la demande</u>:<i> En attente.</i></p>
<% elsif @bid.status == "accepted"%>
<p><u>Statut de la demande</u>:<i>< Félicitations, votre demande a été acceptée !</i></p>
<% else %>
<p>L'association n'a pas souhaité donner suite à votre demande.</p>
<% end %>

<div>
  <p>Cette demande a été émise par <strong><%= @bid.bidder.first_name %> <%= @bid.bidder.last_name %></strong>, représentant l'entreprise <strong><%= @bid.bidder.org_name%>.</strong><p>
  <p><u>Motivations de l'entreprise</u>:</p>
  <p><i><%= @bid.motivation %></i><p>
  <p><u>Ce que l'entreprise propose d'apporter au projet de partenariat</u>:</p>
  <p><i><%= @bid.argument%></i></p>
</div>
<br>
<div>
  <h4>Contactez le représentant de l'entreprise:</h4><br>
  <p>Nom: <%= @bid.contact_name %><p>
  <p>Rôle au sein de l'entreprise: <%= @bid.contact_role %><p>
  <p>Email: <%= @bid.contact_email %><p>
  <p>Numéro de téléphone: <%= @bid.contact_number %><p><br>
</div>

<% if @luli.active && @user == @luli.broker%>
  <div>
    <h4>Votre avis :</h4>
    <p>Attention. Notez que votre choix sera définitif.
      N'hesitez pas a en parler avec la personne de contact
      ou avec <%= link_to 'nous', new_contact_path%>.</p>

      <%= form_tag url_for(action: 'update'), method: 'PUT' do %>
      <%= radio_button :bids, :status, "refused"%>
      Refuser cette proposition<br>
      <%= radio_button :bids, :status, "accepted"%>
      Faire de l'entreprise votre partenaire dans ce projet
      <br><%= button_to "Voici ma décision", luli_bid_path(@luli,@bid), method: :put, class: "btn btn-success m-2" %>
      <% end %>
  </div>
<% end %>
 </div>
 <br>
<div class="bid-return-button">

  <%= link_to "Retour au luli", luli_path(@bid.luli.id), class:"btn btn-primary mr-2"%>
</div>
</div>