config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root "static#home"

  get '/proposez_votre_luli', to: 'static#association_invite'

  get '/presentation', to:'static#presentation'


  resources :static, only: [:home]
  resources :users, except: [:index, :new, :create]
  resources :contacts, only: [:new, :create], path: 'contact'
  resources :lulis do
    resources :bids,except: [:index, :edit, :destroy]
  end

end

app/models/user.rb
class User < ApplicationRecord

  extend FriendlyId
  friendly_id :name, use: :slugged


  ORG_TYPE_LIST = %w(association entreprise site_admin)

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lulis_published, foreign_key: "broker_id",class_name: "Luli"
  has_many :bids_offered, foreign_key: "bidder_id", class_name: "Bid"
  has_many :contacts

  validates :first_name, FIELD_VALIDATIONS
  validates :last_name, FIELD_VALIDATIONS
  validates :org_type, inclusion: {in: ORG_TYPE_LIST, message: "Veuillez choisir une valeur parmi 'association', 'entreprise' et 'site_admin'" }
  validates :org_name, FIELD_VALIDATIONS
  validates :role, FIELD_VALIDATIONS
  validates :email, presence: true, format: { with: EMAIL_REGEX }
  validates_confirmation_of :password

  after_create :new_user_send, :welcome_send

  #########instance methods here##############
  def name
    first_name + " " + last_name
  end

  def is_association
    org_type == 'association'
  end

  def is_entreprise
    org_type == 'entreprise'
  end
  #########mailing methods here###############
  def new_user_send
    AdminMailer.new_user(self).deliver_now
  end

  def welcome_send
    UserMailer.welcome(self).deliver_now
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_current_user

  def show
    # it's really important that here the url not take any params
    # otherwise a person can go to other people's profile
    # the before_action makes sure whatever params is passed, the page stays at current_user profile
  end

  def edit
  end

  def update
    if !@user.update(user_attributes)
      flash[:notice] = "La mise à jour de votre profil à échoué. Avez-vous rempli tous les champs ?"
      render "edit"
    else
      flash[:success] = "Vos modifications ont bien été prises en compte."
      redirect_to user_path(@user.id)
    end
  end

  def destroy
    @user.destroy
  end

  private
  def user_attributes
    params.permit(:first_name,
    :last_name, :org_name, :role)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="container">
  <h4 class="text-center">Mettre à jour mon profil</h4>
  <div class="form" >
    <%= form_tag user_path(@user.id),multipart: true, method: :put do %>
      <div class="row no-gutters mt-5 justify-content-around">
        <div class="form form-group col-md-5">
           <label for="first_name">Votre prénom:</label>
            <input type="text" class="form-control" name="first_name"
              value="<%= @user.first_name%>" />
        </div>

        <div class="form form-group col-md-5">
           <label for="last_name">Votre nom de famille:</label>
             <input type="text" class="form-control"  name="last_name"
               value="<%= @user.last_name%>"/>
        </div>
      </div>

      <div class="row no-gutters mt-5 justify-content-around">
        
        <div class="form form-group col-md-5">
         <label for="last_name">Le nom de l'<%= @user.org_type%> pour laquelle vous travaillez:</label>
         <input type="text" class="form-control"  name="org_name"
             value="<%= @user.org_name%>"/>
          </div>

        <div class="form form-group col-md-5">
         <label for="last_name">L'intitulé de votre poste':</label>
           <input type="text" class="form-control"  name="role"
             value="<%= @user.role%>"/>
         </div>
      </div>


      <div class="text-center mt-5 mb-5 form-group">
           <button type="submit" class="btn btn-primary btn-lg">Mettre à jour</button>
      </div>
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <% end %>
  </div>  
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
	<div class="container-fluid bg-light">
		<div class="container pt-5">
	      <h1 class="text-primary text-left"><%= @user.first_name %> <%= @user.last_name %></h1>
				<div class="profile row d-flex">

					<div class="col-md-6">
					  <%= link_to "Editer mes infos", edit_user_path(current_user), class:"btn btn-outline-secondary mr-3 mt-5 mb-0 ml-4", role:"button" %>
					  <%= link_to "Editer mon mot de passe", edit_user_registration_path(current_user), class:"btn btn-outline-secondary mt-5"%>
	  			</div>
					<div class="col-md-6 text-right text-secondary mb-5 ">
						<p><strong>Email:</strong> <%= @user.email %></p>
						<p><strong>Nom de votre organisme:</strong> <%= @user.org_name%></p>
						<p><strong>Poste actuel:</strong> <%= @user.role %></p>
					</div>

				</div>
				</div>
	</div>
<div class="container"  id="profile_box">


      <% if @user.is_association%>
			  <% if @user.lulis_published.length == 0%>
				  <div class="container">
				  	<h3 class="text-center text-secondary mt-5 mb-5">Vous n'avez pas encore proposé de Luli ! Commencez dès maintenant</h3>
				  	<div class="row justify-content-center mt-5">
							<%= link_to "Proposez votre Luli", new_luli_path, class:"btn btn-block btn-lg btn-warning w-25"%>
				  	</div>
				  </div>
			  <% else%>
				  <%= render "lulis/list", :luli_list => @user.lulis_published.where(admin_validate: false) %>
					<%= render "lulis/list", :luli_list => @user.lulis_published.where(active: true) %>
					<%= render "lulis/list", :luli_list => @user.lulis_published.where(admin_validate: true, active: false) %>
			  <% end%>
			<% elsif @user.is_entreprise%>
			  <% if @user.bids_offered.length == 0%>
				  <div class="container">
				  	<h3 class="text-center text-secondary mt-5 mb-5">Vous n'avez pas encore demandé de mise en relation ! Commencez dès maintenant</h3>
				  	<div class="row justify-content-center mt-5">
					    <%= link_to "Trouvez votre Luli", lulis_path, class:"btn btn-block btn-lg btn-info w-25"%>
						</div>
			  	</div>
			  <% else%>
				  <%= render "bids/list", :bid_list => @user.bids_offered.where(status: 'pending') %>
					<%= render "bids/list", :bid_list => @user.bids_offered.where(status: 'accepted')  %>
			  <% end%>
			<% elsif @user.admin%>
				<div class="container">
					<h3 class="text-center text-secondary mt-5 mb-5">Voici les nouveaux Lulis en attente de validation</h3>
				</div>
				<%= render "lulis/list", :luli_list => Luli.where(admin_validate: false) %>
			<% end %>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>