config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root "static#home"

  get '/proposez_votre_luli', to: 'static#association_invite'

  get '/presentation', to:'static#presentation'


  resources :static, only: [:home]
  resources :users, except: [:index, :new, :create]
  resources :contacts, only: [:new, :create], path: 'contact'
  resources :lulis do
    resources :bids,except: [:index, :edit, :destroy]
  end

end

app/models/luli.rb
class Luli < ApplicationRecord

  PATHOLOGY_LIST = %w(Cardio-Vasculaire
  Dépendances
  Dermatologie
  Maladies_génétiques
  Maladies_infectieuses
  Maladies_rares
  Neurologie
  Oncologie
  Ophtalmologie
  Psychologie
  Respiratoire
  _Prévention
  _Autre)

  PARTNERSHIP_LIST = %w(Sponsoring
  Mécenat_de_compétences
  Co-construction
  A_définir)

  belongs_to :broker, foreign_key:"broker_id", class_name: "User"
  has_many :bids, dependent: :destroy
  has_many :bidders, through: :bids, foreign_key:"bidder_id", class_name: "User"
  has_one_attached :cover_photo
  has_one_attached :attachment

  validates :name, TEXT_VALIDATIONS
  validates :description, TEXT_VALIDATIONS
  validates :request, TEXT_VALIDATIONS
  validates :contact_name, FIELD_VALIDATIONS
  validates :contact_number, phone: true
  validates :contact_email, presence: true, format: { with: EMAIL_REGEX}
  validates :pathology,presence: true, inclusion: {in: PATHOLOGY_LIST}
  validates :partnership, presence: true, inclusion: {in: PARTNERSHIP_LIST}
  validates :comment, length: 1..5000
  validates :name, uniqueness: { scope: :broker_id,
      message: "Vous avez un luli au même nom, veuillez choisir un nouveau nom pour ce projet." }

  after_create :new_luli_send
  after_update :luli_update_notification

  #########instance methods here##############
  def unvalidate
    admin_validate == false
  end

  def archived
    admin_validate && (!active)
  end
  #########mailing methods here###############

  def new_luli_send
    AdminMailer.new_luli(self).deliver_now
    LuliMailer.new_luli(self).deliver_now
  end

  def luli_update_notification
    AdminMailer.luli_update(self).deliver_now
    LuliMailer.luli_update(self).deliver_now
  end
end

app/controllers/lulis_controller.rb
class LulisController < ApplicationController
  before_action :get_current_user, except:[:index]
  before_action :get_current_luli, except: [:index, :new, :create]
  before_action :can_create_luli, only: [:new, :create]
  before_action :can_edit_luli, only: [:edit, :update, :destroy]
  before_action :get_pathologies, only: [:new, :create, :edit, :update]
  before_action :get_partnerships, only: [:new, :create, :edit, :update]

  def index
    @active_lulis = Luli.all.where(active: true)
    @unvalidate_lulis = Luli.all.where(admin_validate: false)
    @archived_lulis = Luli.all.where(active: false, admin_validate: true)
    if @archived_lulis.length >= 3
      @cover_luli = @archived_lulis[-1]
      @sliding_lulis = @archived_lulis[0,2]
    end
  end

  def show
    no_bid_yet
  end

  def new
    is_admin
    @luli = Luli.new(contact_name: @user.name, contact_email: @user.email, broker: @user)
  end

  def create
    @luli = Luli.new(luli_attributes.merge(broker: @user))
    if @luli.invalid?
      flash[:notice] = "Votre Luli n'a pas été crée. Avez vous rempli tous les champs?"
      render :new
    elsif !cover_photo.present?
      flash[:notice] = "Veuillez télécharger une photo de couverture pour votre Luli."
      render :new
    elsif @luli.save && !saved_attachments?
        flash[:notice] = "Nous n'avons pas réussi à sauvegarder votre pièce-jointe. Veuillez ré-essayer."
        redirect_to edit_luli_path(@luli)
    else
        flash[:success] = "Votre Luli a été crée avec succès ! Une fois validé par l'administrateur, il sera visibile sur le site dans l'onglet 'Entreprises, trouvez votre Luli'."
        redirect_to luli_path(@luli)
    end
  end

  def edit
    is_admin
  end

  def update
    if @user == @luli.broker
      @luli.update(luli_attributes)
    elsif @user.admin
      @luli.update(admin_attributes)
    end

    if @luli.admin_validate
      @luli.update(active: true)
    end

    if @luli.invalid?
      flash[:notice] = "Modifications non enregistrées. Veuillez réessayer."
      render 'edit'
    elsif cover_photo.present? && !attach_photo
      flash[:notice] = "Photo non enregistrée. Veuillez ré-essayer."
      render 'edit'
    elsif attachment.present? && !attach_file
      flash[:notice] = "Pièce jointe non enregistrée. Veuillez réessayer."
      render 'edit'
    else
      flash[:success] = "Modifications reussies."
      redirect_to luli_path(@luli)
    end
  end

  def destroy
    @luli.destroy
    flash[:success] = "Ce Luli a bien été supprimé."
    redirect_to root_path
  end


  private
  def get_current_luli
    @luli = Luli.find(params[:id])
  end

  def can_edit_luli
    if @user.admin || @user == @luli.broker
      true
    else
      flash[:notice] = "Vous n'avez pas accès à cette page."
      redirect_to luli_path(@luli)
    end
  end

  def can_create_luli
    if @user.is_association
      true
    else
      flash[:notice] = "Seules les associations peuvent creer des Lulis."
      redirect_to root_path
    end
  end

  def no_bid_yet
    bid_lulis = @user.bids_offered.map{|b| b.luli}
    @no_bid_yet = !bid_lulis.include?(@luli) && @user.org_type == "entreprise"
  end

  def luli_attributes
    params.permit(:association_description, :name, :pathology, :partnership, :description, :request, :comment, :contact_name, :contact_number, :contact_email)
  end

  def admin_attributes
    params.permit(:association_description, :description, :request, :admin_validate)
  end


  def cover_photo
    params.permit(:cover_photo)[:cover_photo]
  end

  def attachment
    params.permit(:attachment)[:attachment]
  end

  def attach_photo
    @luli.cover_photo.attach(cover_photo)
    @luli.cover_photo.attached?
  end

  def attach_file
    @luli.attachment.attach(attachment)
    @luli.attachment.attached?
  end

  def saved_attachments?
    attach_photo && (attachment.blank? || attach_file)
  end

  def get_pathologies
    @pathologies = Luli::PATHOLOGY_LIST
  end

  def get_partnerships
    @partnerships = Luli::PARTNERSHIP_LIST
  end

end

app/helpers/lulis_helper.rb
module LulisHelper
end

app/views/lulis/_form.html.erb
<%= form_tag url_for(action: action), method: method, multipart: true, class:"form-container" do %>
    <div class="row no-gutters mt-5">
      <div class="first-luli form-col">

        <div>
          <h2 class="text-link ml-3">Pour commencer: </h2>

          <div class="my-4 mx-3">
            <div class="form-group col-md ml-3">
              <%= label_tag 'name', 'Nom de votre projet*'%>
              <%= text_field_tag 'name', @luli.name, disabled: @is_admin, class: "form-control", placeholder: 'Entre 5 et 5000 carctères' %>
            </div>

            <div class="form-group row no-gutters d-flex justify-content-around mt-5">
              <div class="form-group col-md-5 ">
                <%= label_tag 'pathology', 'Votre projet vise quelle pathologie ?'%><br>
                <%= select_tag 'pathology', options_for_select(@pathologies, @luli.pathology), disabled: @is_admin, class: "my-3 p-1 ml-0 form-control"%>
              </div>

              <div class="form-group col-md-5">
                <%= label_tag 'partnership', 'Quel partenariat recherchez-vous ?'%>
                <br>
                <%= select_tag 'partnership', options_for_select(@partnerships, @luli.partnership), disabled: @is_admin, class: "my-3 p-1 form-control"%>
              </div>
            </div>
          </div>
        </div>


        <div>
          <h2 class="text-link ml-3">Parlons-en un peu plus: </h2>
           <p class="ml-3"><small class="font-italic">(Ces champs pourront être modifiés par l'administrateur du site)</small></p>
          <div class="form-group col-md my-5 ml-3">

            <div class="luli-fields form-group col-md">
              <%= label_tag 'description', "Parlez-nous de votre association.*"%>

              <%= text_area_tag 'association_description', @luli.association_description,class: "form-control", placeholder: 'Entre 5 et 5000 caractères' %>
            </div>
             <div class=" luli-fields form-group col-md-12">
              <%= label_tag 'association_description', "Parlez-nous de votre projet de partenariat.*"%><br>
              <%= text_area_tag 'description', @luli.description, class: "form-control overflow-auto", placeholder: 'Entre 5 et 5000 caractères' %>
            </div>
            <div class="luli-fields form-group col-md-12">
              <%= label_tag 'request', "Parlez-nous de votre besoin.*"%><br>
              <%= text_area_tag 'request', @luli.request, class: "form-control", placeholder: 'Entre 5 et 5000 caractères' %>
            </div>

            <div class="luli-fields form-group col-md-12">
              <%= label_tag 'comment', "Avez vous d'autres précisions à apporter ?"%><br>
              <%= text_area_tag 'comment', @luli.comment, disabled: @is_admin, class: "form-control", placeholder: 'Entre 1 et 5000 caractères'%>
            </div>
            </div>
        </div>

        <% if !@is_admin %>
        <div>
          <h2 class="text-link ml-3">Fichiers à télécharger: </h2>
          <p class="ml-3">Veuillez télécharger une photo <strong>(obligatoire)</strong> et une pièce jointe (facultatif)</p><br>
          <div class="col d-flex justify-content-between ml-3">

          <div class="luli-fields form-group col-md">
            <%= label_tag 'cover_photo', "Photo"%><br>
            <%= file_field_tag 'cover_photo'%>
          </div>

          <div class="luli-fields form-group col-md mb-5">
            <%= label_tag 'attachment', "Pièce jointe"%><br>
            <%= file_field_tag 'attachment'%>
          </div>
        </div>
        <% end %>

        <div>
            <h2 class="text-link ml-3">Personne à contacter : </h2>
            <div class="container ml-3 mt-4">

              <div class="row">
                  <%= label_tag 'org_name', 'Nom de votre association'%>
                  <%= text_field_tag 'org_name', @luli.broker&.org_name, class: "form-control",readonly:true %>
              </div>

              <div class="row">
                <div class="form-group col-md-6 mt-4 mr-5">
                    <%= label_tag 'contact_name', 'Personne à contacter*'%>
                    <%= text_field_tag 'contact_name', @luli.contact_name, disabled: @is_admin, class: "form-control", placeholder: 'Entre 1 et 100 caractères' %>
                </div>
                <div class="form-group col-md-6 mt-4">
                    <%= label_tag 'contact_number', 'Uniquement les chiffres sans indicadif ni séparateur. Ex: 0607070750'%>
                    <%= text_field_tag 'contact_number', @luli.contact_number, disabled: @is_admin, class: "form-control", placeholder: '10 chiffres' %>
                </div>
              </div>
              <div class="row">
                  <%= label_tag 'contact_email', 'Email*'%>
                  <%= text_field_tag 'contact_email', @luli.contact_email, disabled: @is_admin, class: "form-control", placeholder: 'exemple@email.com' %>
              </div>

            </div>
            <p class="font-italic mt-5 ml-3">(*)Champs obligatoires.</p>
        </div>

        <div>
          <% if @is_admin %>
            <%= check_box_tag :admin_validate, true, false%>
            Cochez pour valider ce luli<br>
          <% end %>
        </div>
      </div>

    </div>


    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <div class="luli-btn">
      <% submit_text = @is_admin ? "Modifier / Valider ce Luli" : "Proposer mon luli"%>
      <%= button_to submit_text, lulis_path(@luli.id), method: method, class: "btn btn-primary" %>
    </div>

<% end %>

app/views/lulis/_intro.html.erb
<div class="container"></div>
<div class="container-fluid mb-0 mt-5">
  <div class="px-5 bg-primary text-white">
    <div class="p-5">
      <h1 class="text-center text-white">Association, proposez un Luli</h1>
      <div class="text-center px-5 pt-5">
        <p class="text-justify px-5">
        Vous avez une idée de projet à développer et vous recherchez une entreprise partenaire ? Proposez ici votre Luli.
        En remplissant le formulaire ci-dessous, votre proposition de Luli nous sera envoyé. Nous vous contacterons ensuite pour vous aider à définir les contours de ce projet de partenariat.
        Une fois le Luli validé ensemble, il sera visible sur notre plateforme. Les entreprises pourront alors le consulter et vous proposer d'en être les partenaires industriels.
        A tout moment, Lucky link fera le lien.
        Selon vos besoins, nous pourrons répondre à un besoin d'accompagnement ponctuel ou à longue durée afin de faire de ce projet un partenariat gagnant-gagnant.
        </p>
        <br>
      </div>
    </div>
  </div>
</div>

app/views/lulis/_list.html.erb
<div class="container mt-5 ">
<% luli_list.each do |luli| %>
  <div class=" row mb-2 no-gutters">
    <div class="col-md-12">
      <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative bg-white">
        <div class="col p-4 d-flex flex-column position-static border-right border-light ml-3">
          <p>
            <% if !luli.admin_validate %>
              <span class="btn-info p-1 btn-sm text-white">En attente</span>
            <% elsif luli.active%>
                <span class="btn-success btn-sm p-1 text-white">En recherche</span>
            <% else %>
                <span class="btn-warning btn-sm p-1 text-white ">Partenariat trouve</span>
            <% end %>
          </p>
          <h3 class="mb-0 resizing-title"><%=luli.name%></h3><br>
          <div class="mb-1 text-muted">
            <p>Proposé par <strong><%= luli.broker.org_name%></strong></p>
            <p>Publié le: <%= luli.created_at.to_date%></p>
            <p><span class="badge badge-info"><%= luli.pathology %></span>
              <span class="badge badge-warning"><%= luli.partnership %></span></p>
          </div>
          <%= button_to "Voir le luli", luli_path(luli.id), method: :get, class:"btn btn-outline-primary mr-2 w-25 see_luli"%>
        </div>
        <div class="col-md-6 d-none d-lg-block">
            <% if luli.cover_photo.attached?%> <%= image_tag luli.cover_photo, style:'object-fit: cover; height: 310px; width: 100%; display: block;' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/lulis/create.html.erb
<h1>Lulis#create</h1>
<p>Find me in app/views/lulis/create.html.erb</p>

app/views/lulis/edit.html.erb
<h1 class="luli-title">Modifier mon Luli</h1>
<div>
	<div class="mx-5">
		<div class="mx-5">
			<%= render "form", :method => "PUT", :action => "update"%>
		</div>
	</div>		
</div>

app/views/lulis/index.html.erb
<body class="bg-light">
  <% if current_user && current_user.admin %>
    <div class="container text-secondary mt-5">
      <h3>Cher administrateur, ces nouveaux Luli attendent la validation:</h3><br>
    </div>
    <%= render "list", :luli_list => @unvalidate_lulis %>
  <% end %>

  <div class="container text-center text-secondary mt-5">
    <h3>Les projets des associations en recherche d'un partenaire industriel</h3><br>
    <p>Bien trop souvent, des entreprises élaborent des projets complexes et coûteux sans consulter les praticiens, patients ou autre public auquel elles s'adressent. Pourtant les associations ont la connaissance des réalités et besoins du terrain.<br>
    Sur notre plateforme, les associations proposent aux entreprises des Luli : des projets  à co-créer en partenariat.<br>
    Nous sommes fiers de tous ces projets et espérons que vous y trouverez votre Luli.</p>
  </div>
  <%= render "list", :luli_list => @active_lulis %>

  <% if @archived_lulis.length >=3 %>
  <div class="bg-primary p-3 text-center mt-5">
    <h3 class="text-white mt-5 mb-5">Ces Lulis ont trouvé leur entreprise partenaire grâce à Lucky Link</h3></p>
  </div>

  <div class="bd-example bg-light p-5 container mt-5">
    <div id="carouselExampleCaptions" class="row carousel slide mx-5 px-5" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
      </ol>

      <div class="carousel-inner">
        <div class="carousel-item active">
        <%= image_tag @cover_luli.cover_photo, class:"sliding_lulis_cover"%>
          <div class="carousel-caption  justity-content-center">
            <h5><%= link_to @cover_luli.name, luli_path(@cover_luli), class:"text-dark"%></h5>
            <p><%= @cover_luli.broker.org_name%></p>
          </div>
        </div>
        <% @sliding_lulis.each do |s| %>
        <div class="carousel-item">
        <%= image_tag s.cover_photo, class:"sliding_lulis_cover"%>
          <div class="carousel-caption  justity-content-center">
            <h5><%=link_to s.name, luli_path(s), class:"text-dark"%></h5>
            <p><%= s.broker.org_name%></p>
          </div>
        </div>
        <% end %>
      </div>
        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  <% end %>
  <div class="p-5">
  </div>
</body>

app/views/lulis/new.html.erb
	<div>
		<%= render "intro"%>

		<div class="mx-5">
			<div class="mx-5">

				<h1 class="text-center text-primary mt-5 pt-5">Proposez ici votre Luli</h1>
				<%= render "form", :method => "POST", :action => "create"%>
			</div>
		</div>
	</div>

app/views/lulis/show.html.erb
<div class="row no-gutters my-5 px-5 text-center">
  <div class="lulishow col px-5">
    <p>
      <% if !@luli.admin_validate %>
        <span class="btn-info p-2 text-white">En attente</span>
      <% elsif @luli.active%>
          <span class="btn-success p-2 text-white">En recherche</span>
      <% else %>
          <span class="btn-warning p-2 text-white ">Partenariat trouve</span>
      <% end %>
      <% if @user == @luli.broker %>
        <span class="font-italic ml-3">Ceci est votre luli </span>
      <% elsif (@user.bids_offered.map{|b| b.luli}.include?(@luli))  %>
        <span class="font-italic ml-3">Vous avez une demande en cours </span>
      <% end %>
    </p>
    <h3 class="card-title text-primary text-center"><%= @luli.name %></h3>
    <h6>Crée par <strong><%= @luli.broker.org_name%></strong></h6>
    <p class="card-text text-center"><strong>Date de création:</strong> <%= @luli.created_at.to_date %></p>
    <p class="card-text text-center"><strong>Pathologie concernée:</strong><br> <%= @luli.pathology %></p>
    <p class="card-text text-center"><strong>Partenariat recherché:</strong><br> <%= @luli.partnership %></p>
    <% if @luli.attachment.attached?%>
      <%= link_to 'Télécharger la pièce jointe', @luli.attachment, target: :blank%>
    <% else %><br>
      <h6>Il n'y a pas de pièce jointe au luli.</h6>
    <% end %>
  </div>
  <div class="col-md-6 d-none d-lg-block mt-4">
    <% if @luli.cover_photo.attached?%>
      <%= image_tag @luli.cover_photo, style:'object-fit: cover; max-height: 520px; width: 100%; display: block;' %>
    <% end %>
  </div>
</div>

<div class="row no-gutters bg-light px-5 pb-3">
  <div class="lulishow col mb-3 px-5">
    <p class="card-text mt-4"><strong>Description:</strong><br> <%= @luli.description %></p>
  </div>
</div><br>
<div class="row no-gutters bg-light px-5 pb-3">
  <div class="lulishow col mb-3 px-5">
    <p class="card-text mt-4"><strong>Ce dont nous avons besoin:</strong><br> <%= @luli.request %></p>
  </div>
</div><br>
<div class="row no-gutters bg-light px-5 pb-3">
  <div class="lulishow col mb-3 px-5">
    <p class="card-text mt-4 mb-2"><strong>Un mot sur l'association:</strong><br> <%= @luli.association_description %></p>
    <b>
  </div>
</div>

<div class="row no-gutters px-5">
  <% unless @user.org_type =="entreprise" %>
    <div class="my-5 px-5">
      <h4>Informations de contact:</h4>
      <h6>Nom: <%= @luli.contact_name %></h6>
      <h6>Numéro de téléphone: <%= @luli.contact_number %></h6>
      <h6>Email: <%= @luli.contact_email %></h6>
    </div>
  <% end %>
</div>

<div class="row no-gutters px-5 pb-5">
  <div class="px-5">
    <% unless @luli.bids.length == 0%>
      <% if @user.is_entreprise%>
        <h5 class="mt-4"><%= @luli.bids.length%> entreprise ont demandé une mise en relation.</h5>
      <% else %>
        <h5 class="mt-4">Ces entreprises ont demandé une mise en relation:</h5>
        <% @luli.bids.each do |bid| %>
          <% if @user == @luli.broker %>
            <%= link_to bid.bidder.org_name, luli_bid_path(bid.luli.id, bid.id) %>
            <br>
          <%else%>
            <%= bid.bidder.org_name %><br>
          <% end %>
        <% end %>
      <% end %>


    <% end %>
  </div>
</div>

<div class="row no-gutters px-5 pb-5">
  <div class="mt-5 px-5">
    <% if @user.admin && (!@luli.admin_validate)%>
      <%= link_to 'Modifier ou valider ce luli', edit_luli_path(@luli), class: "btn btn-primary"%>
    <% elsif @user == @luli.broker %>
      <div class="d-flex flex-direction-row flex-wrap">
        <%= link_to 'Modifier le luli', edit_luli_path(@luli), method: :get, class: "btn-luli-show btn btn-primary mr-5"%>
        <%= link_to "Supprimer le luli", luli_path(@luli), method: :delete, class: "btn-luli-show btn btn-outline-danger" %>
      </div>
    <% elsif @user.org_type == "entreprise" && (!@user.bids_offered.map{|b| b.luli}.include?(@luli))%>
      <%= link_to "Ce luli m'interesse", new_luli_bid_path(@luli), method: :get, class: "btn-lg btn-primary ml-5 my-5" %>
      <% end %>
  </div>
</div>
</div>
</div>
</div>

app/views/lulis/update.html.erb
<h1 class="luli-title">Créer mon Luli</h1>

<%= form_tag url_for(action: 'create'), method: 'POST', class:"form-container" do %>
    
    <div class="form-row">

      <div class="form-group col-md-4">
        <%= label_tag 'contact_name', 'Contact name:'%>
        <%= text_field_tag 'contact_name', @luli.contact_name, class: "form-control" %>
      </div>

      <div class="form-group col-md-4">
        <%= label_tag 'contact_number', 'Contact number:'%>
        <%= text_field_tag 'contact_number', @luli.contact_number, class: "form-control" %>
      </div>

      <div class="form-group col-md-4">
        <%= label_tag 'contact_email', 'Contact email:'%>
        <%= text_field_tag 'contact_email', @luli.contact_email, class: "form-control" %>
      </div>

    </div>

    <div class="form-row">

      <div class="form-group col-md-4">
        <%= label_tag 'name', 'Name:'%>
        <%= text_field_tag 'name', @luli.name, class: "form-control" %>
      </div>

      <div class="form-group col-md-4">
        <%= label_tag 'description', 'Description:'%>
        <%= text_field_tag 'description', @luli.description, class: "form-control" %>
      </div>

      <div class="form-group col-md-4">
        <%= label_tag 'request', 'Request:'%>
        <%= text_field_tag 'request', @luli.request, class: "form-control" %>
      </div>

    </div>

      <%= button_to "Modifer mon luli", lulis_path(@luli.id), method: :put, class: "btn btn-success" %>

  <% end %>