config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root "static#home"

  get '/proposez_votre_luli', to: 'static#association_invite'

  get '/presentation', to:'static#presentation'


  resources :static, only: [:home]
  resources :users, except: [:index, :new, :create]
  resources :contacts, only: [:new, :create], path: 'contact'
  resources :lulis do
    resources :bids,except: [:index, :edit, :destroy]
  end

end

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show text-center m-0 p-4" role="alert">
    <%= msg %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
  <div class="page-footer sticky-bottom container-fluid text-secondary py-3 " style="background-color:#ebebeb; font-size:0.9em;">
    <div class="row no-gutters">

      <div class="col text-center">
        <%= link_to "| Lucky Link", root_path, class:"navlink", id: "home_footer"%>
      </div>

      <div class="col text-center">
        <%= link_to "| Qu'est-ce qu'un Luli ?", presentation_path, class:"navlink", id:"what_is_footer"%>
      </div>

      <div class="col text-center">
        <%= link_to "| Contactez-nous", new_contact_path, class:"navlink", id: "contact_footer"%>
      </div>

    </div>
  </div>

  <div class="bg-secondary text-white">
    <div class="container">

        <div class="footer-copyright text-center py-1"><small>© 2019 Copyright: Lucky Link</small>
        </div>

    </div>
  </div>

app/views/layouts/_nav.html.erb
<header>
  <nav class="navbar navbar-expand-xl navbar-dark bg-white text-primary p-0">
    <div class="logo ml-5">
      <%= link_to image_tag("logo-print-hd-transparent.png", :alt => "Lucky Link logo"), root_path, id:"logo_nav" %>
    </div>
    <button id="the_toggler" class="navbar-toggler bg-primary p-2" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse " id="navbarsExample05">

      <div class="nav-nav container d-flex flex-direction-row justify-content-around p-0 ml-5">
        <div>
          <%= link_to "| Qu'est-ce qu'un Luli?", '/presentation', class:"mr-5", id:"what_is_nav"%>
          <%= link_to "| Entreprise, trouvez votre Luli", lulis_path, class:"mr-5", id:"lulis_nav"%>
          <% if !current_user %>
            <%= link_to "| Association, proposez votre Luli", "/proposez_votre_luli", class:"mr-5" , id:"new_luli_nav_tourist"%>
          <% elsif current_user && current_user.is_association%>
            <%= link_to "| Association, proposez un Luli", new_luli_path, class:"mr-5", id:"new_luli_nav_association"%>
          <% end %>
          <%= link_to "| Contactez-nous", new_contact_path, class:"mr-5", id:"contact_nav"%>
        </div>
        <div>
          <% if current_user %>
            <% if current_user.admin %>
            <%= link_to "| Entrée admin", rails_admin_path, class:"ml-3 font-weight-bold", id:"admin_nav"%>
            <% end %>
            <%= link_to "| Mon Profil", user_path(current_user), class:"ml-3", id:"profile_nav"%>
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class:"ml-3 btn btn-outline-primary btn-sm", id:"signout_nav" %>
          <% else %>
            <%= link_to "Inscription", new_user_registration_path, class:"ml-5 mr- btn btn-primary btn-sm", id: "inscription_nav" %>
            <%= link_to "Connexion", new_user_session_path, class:"ml-3 mr-5 btn btn-outline-primary btn-sm", id: "connexion_nav"%>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Lucky Link</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "bootstrap_custom.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/nav"%>
    <%= render "layouts/flash"%>

    <%= yield %>

    <%= render "layouts/footer"%>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>